<section class="about section--fullHt">
  <h2 class="t-title--40l">&lt; about &gt;</h2>
  <div class="about_contentWrapper">
    <img src="https://via.placeholder.com/500" class="about_image" alt="Sharon" />
    <div class="about_text">
      <p class="t-body--18l">Lorem ipsum dolor est sit amet.</p>
      <button class="btn--secondary t-title--20b t-caps">Download resume</button>
      <div>
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-codepen"></i></a>
      </div>
    </div>
  </div>
</section>