<section class="about section--fullHt">
  <h2>&lt; about &gt;</h2>
  <div class="about_contentWrapper">
    <img src="https://via.placeholder.com/500" class="about_image" alt="Sharon" />
    <div class="about_text">
      <h3>Some highlighted text goes here</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <button>Download resume</button>
      <div>
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-codepen"></i></a>
      </div>
    </div>
  </div>
</section>