<div class="stickyWrapper">
<header class="header">
  <a href="/index.php" class="header_name t-title--20b">Sharon Hartsell</a>
  <nav class="nav">
    <button class="nav_toggle">
      <i class="fas fa-bars"></i>
      <span class="nav_toggleText">Menu</span>
    </button>
    <ul class="nav_list section--fullHt">
      <li><a href="#">Home</a></li>
      <li><a href="#">Work</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </nav>
</header>