<div class="stickyWrapper">
<header class="header">
  <a href="/index.php" class="header_name t-title--20b">Sharon Hartsell</a>
  <nav class="nav">
    <button class="nav_toggle">
      <i class="fas fa-bars"></i>
      <span class="nav_toggleText">Menu</span>
    </button>
    <div class="nav_listWrapper">
      <ul class="nav_list">
        <li class="nav_listItem">
          <a href="/index.php" class="nav_link">home</a>
        </li>
        <li class="nav_listItem">
          <a href="/index.php#work" class="nav_link">work</a>
        </li>
        <li class="nav_listItem">
          <a href="/index.php#about" class="nav_link">about</a>
        </li>
        <!-- <li class="nav_listItem">
          <a href="/index.php#contact" class="nav_link">contact</a>
        </li> -->
      </ul>
    </div>
  </nav>
</header>