<section class="work section--fullHt">
  <h2>&lt; work &gt;</h2>
  <ul class="work_projectList">
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    <li class="work_projectListItem">
      <h3>Project Title</h3>
      <p>Lorem ipsum dolor est sit amet.</p>
      <a href="work-detail.php" class="work_projectBtn">See Details</a>
    </li>
    
  </ul>
</section>